name: Run Hackolade CLI using Docker Compose in CI
on:
    workflow_dispatch:
jobs:
 run-hackolade-with-compose:
    runs-on: ubuntu-latest
    env:
        # License key must be anaged as a secret (Repository or Organization)
        HACKOLADE_KEY: ${{ secrets.HACKOLADE_CONCURRENT_LICENSE_KEY }}
        REPOSITORY_DIR_IN_CONTAINER: '/github/workspace/repository'
        OUTPUT_DIR_IN_CONTAINER: '/home/hackolade/Documents/output'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create logs and output directories
        id: create-logs-and-output-directories
        run: |
          mkdir -p output
          mkdir -p logs

      - name: Build Hackolade Docker image
        id: build-studio-cli-docker-image
        run: |
          docker build --no-cache --pull -t hackolade:latest .

      - name: Retrieve image identifier for GHA
        id: retrieve-identifier-for-hackolade-studio-licensing
        run: echo "identifier=$(docker compose run -i --rm --entrypoint show-computer-id.sh hackoladeStudioCLI)" >> $GITHUB_OUTPUT

      - name: Validate concurrent license
        id: validate-concurrent-hackolade-studio-license
        run: |
          docker compose run --rm hackoladeStudioCLI validatekey \
            --key "${{ env.HACKOLADE_KEY }}" \
            --identifier "${{ steps.retrieve-identifier-for-hackolade-studio-licensing.outputs.identifier }}"

      - name: Generate HTML documentation for Couchbase travel.json example model
        id: generate-html-doc-travel-model
        run: |
          # Working directory in container is set to REPOSITORY_DIR_IN_CONTAINER
          docker compose run --rm hackoladeStudioCLI genDoc \
            --model=travel.json \
            --format=HTML \
            --doc=${{ env.OUTPUT_DIR_IN_CONTAINER }}/travel.html
      - name: Retrieve Hackolade logs of documentation generation
        run: |
          docker run --rm --init \
            -u root \
            -v hackolade-studio-logs:/logs \
            -v "${PWD}/logs:/logs-on-host" \
            --entrypoint cp \
            hackolade:latest -r /logs /logs-on-host/logs-doc-generation

      - name: FE - Generate jsonschema file for travel.json example model
        id: generate-fe-jsonschema-for-travel-model
        run: |
          # Working directory in container is set to REPOSITORY_DIR_IN_CONTAINER
          docker compose run --rm hackoladeStudioCLI forweng \
            --model=travel.json \
            --jsonschemacompliance full \
            --skipUndefinedLevel \
            --structuredpath false \
            --path ${{ env.OUTPUT_DIR_IN_CONTAINER }} \
            --outputtype jsonschema

      - name: Retrieve Hackolade output files from volume
        run: |
          docker run --rm --init \
            -u root \
            -v hackolade-studio-output:/output \
            -v "${PWD}/output:/output-on-host" \
            --entrypoint cp \
            hackolade:latest -r /output /output-on-host/.

      - name: Retrieve Hackolade logs for jsonschema generation
        run: |
          docker run --rm --init \
            -u root \
            -v hackolade-studio-logs:/logs \
            -v "${PWD}/logs:/logs-on-host" \
            --entrypoint cp \
            hackolade:latest -r /logs /logs-on-host/logs-fe-jsonschema-generation

      - name: Tear down
        run: |
          docker compose down -v

      - name: Prepare generated artifacts
        id: prepare-hackolade-studio-output
        run: |
          cp ./output/output/travel.html ./documentation/.
          cp -r ./output/travel-sample/* ./generated/.
      # https://github.com/marketplace/actions/create-pull-request
      - name: Open Pull Request with generated documentation
        id: open-pr-with-updated-doc
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: ./documentation/travel.html,./generated/travel-sample
          branch: update-documentation
          branch-suffix: timestamp
          title: Update HTML documentation and jsonschema sample for travel.json data model
